reading things

In [1]:
import xarray as xr
import pandas as pd
import numpy as np
from scipy.spatial.distance import cdist

In [20]:
ds = xr.open_dataset("data/era5_november_2025_data.nc", engine="netcdf4")

In [21]:
ds.indexes

Indexes:
    valid_time      DatetimeIndex(['2025-11-01'], dtype='datetime64[ns]', name='valid_time',
              freq=None)
    pressure_level  Index([1000.0,  975.0,  950.0,  925.0,  900.0,  875.0,  850.0,  825.0,  800.0,
        775.0,  750.0,  700.0,  650.0,  600.0,  550.0,  500.0,  450.0,  400.0,
        350.0,  300.0,  250.0,  225.0,  200.0,  175.0,  150.0,  125.0,  100.0,
         70.0,   50.0,   30.0,   20.0,   10.0,    7.0,    5.0,    3.0,    2.0,
          1.0],
      dtype='float64', name='pressure_level')
    latitude        Index([ 43.0, 42.75,  42.5, 42.25,  42.0, 41.75,  41.5, 41.25,  41.0, 40.75,
        40.5, 40.25,  40.0, 39.75,  39.5, 39.25,  39.0, 38.75,  38.5, 38.25,
        38.0],
      dtype='float64', name='latitude')
    longitude       Index([ -80.0, -79.75,  -79.5, -79.25,  -79.0, -78.75,  -78.5, -78.25,  -78.0,
       -77.75,  -77.5, -77.25,  -77.0, -76.75,  -76.5, -76.25,  -76.0, -75.75,
        -75.5, -75.25,  -75.0, -74.75,  -74.5, -74.25,  -74.0, -73.75,  -73.5,
       -73.25,  -73.0, -72.75,  -72.5, -72.25,  -72.0, -71.75,  -71.5, -71.25,
        -71.0, -70.75,  -70.5, -70.25,  -70.0],
      dtype='float64', name='longitude')

In [22]:
df = ds.to_dataframe()

In [23]:
print(df.sample(15))

                                                       t          u         v  \
valid_time pressure_level latitude longitude
2025-11-01 650.0          38.00    -73.75     268.371338  20.904800 -0.058471
           950.0          39.75    -70.00     279.710938   9.019507 -0.743195
           7.0            42.25    -71.50     221.068222  19.211655 -3.137222
           800.0          42.25    -78.00     268.963379  14.375381 -2.251667
           450.0          38.00    -73.75     251.372025  31.322525  1.627357
           650.0          40.00    -79.75     265.227783  19.559097 -3.639037
           600.0          41.25    -71.75     260.761475  21.259125  0.529176
           5.0            39.75    -72.25     227.971680  29.951904 -0.098206
           875.0          42.00    -74.00     272.398071  10.171829 -1.944388
           825.0          43.00    -74.50     269.127075  13.191299 -2.365679
           500.0          40.50    -70.00     253.750061  27.086411  2.594049
           950.0          41.00    -74.75     277.716797   5.952613 -0.392120
           800.0          42.00    -75.25     269.081543  13.471085 -3.343464
           125.0          42.75    -75.25     216.209488  27.942123 -0.446624
           3.0            42.00    -70.50     234.950638  37.403290 -0.263580

                                                     w  number expver
valid_time pressure_level latitude longitude
2025-11-01 650.0          38.00    -73.75     0.019619       0   0001
           950.0          39.75    -70.00     0.048091       0   0001
           7.0            42.25    -71.50     0.001024       0   0001
           800.0          42.25    -78.00     0.004732       0   0001
           450.0          38.00    -73.75     0.029981       0   0001
           650.0          40.00    -79.75    -0.012546       0   0001
           600.0          41.25    -71.75     0.084607       0   0001
           5.0            39.75    -72.25     0.000402       0   0001
           875.0          42.00    -74.00     0.296242       0   0001
           825.0          43.00    -74.50     0.089550       0   0001
           500.0          40.50    -70.00     0.043508       0   0001
           950.0          41.00    -74.75     0.091975       0   0001
           800.0          42.00    -75.25     0.025301       0   0001
           125.0          42.75    -75.25     0.002642       0   0001
           3.0            42.00    -70.50    -0.000131       0   0001

In [ ]:
df = df.reset_index()

In [25]:
df.index.name = 'id'

In [26]:
df

,valid_time,pressure_level,latitude,longitude,t,u,v,w,number,expver
id,,,,,,,,,,
0,2025-11-01,1000.0,43.0,-80.00,278.512695,2.199965,0.133451,0.026815,0,0001
1,2025-11-01,1000.0,43.0,-79.75,278.684570,2.645766,0.173002,0.037679,0,0001
2,2025-11-01,1000.0,43.0,-79.50,278.885742,3.543715,0.200834,0.046468,0,0001
3,2025-11-01,1000.0,43.0,-79.25,278.932617,3.798110,0.277006,-0.003520,0,0001
4,2025-11-01,1000.0,43.0,-79.00,278.817383,3.061294,0.398100,-0.063273,0,0001
...,...,...,...,...,...,...,...,...,...,...
31852,2025-11-01,1.0,38.0,-71.00,253.412796,71.787094,8.202271,0.000045,0,0001
31853,2025-11-01,1.0,38.0,-70.75,253.438187,72.001938,8.276489,0.000078,0,0001
31854,2025-11-01,1.0,38.0,-70.50,253.468460,72.208969,8.352661,0.000109,0,0001
31855,2025-11-01,1.0,38.0,-70.25,253.501663,72.408188,8.428833,0.000135,0,0001
31856,2025-11-01,1.0,38.0,-70.00,253.536819,72.599594,8.503052,0.000152,0,0001

In [27]:
df.to_csv("data/era5_november_2026_data.csv", index=True)

In [ ]:
new_df = pd.read_csv("era5_october_data.csv", index_col=0, parse_dates=True)

In [14]:
new_df

,pressure_level,latitude,longitude,u,v,number,expver
valid_time,,,,,,,
2025-10-01,300.0,43.0,-80.00,14.790093,-5.906804,0,1
2025-10-01,300.0,43.0,-79.75,14.774468,-5.697331,0,1
2025-10-01,300.0,43.0,-79.50,14.770562,-5.480046,0,1
2025-10-01,300.0,43.0,-79.25,14.782281,-5.258855,0,1
2025-10-01,300.0,43.0,-79.00,14.803765,-5.025945,0,1
...,...,...,...,...,...,...,...
2025-10-01,300.0,38.0,-71.00,22.393608,2.610774,0,1
2025-10-01,300.0,38.0,-70.75,22.335014,2.602962,0,1
2025-10-01,300.0,38.0,-70.50,22.254936,2.592708,0,1
2025-10-01,300.0,38.0,-70.25,22.168999,2.581965,0,1
2025-10-01,300.0,38.0,-70.00,22.086967,2.568782,0,1

In [23]:
target_lat, target_lon = 40.0, -75.0

coords = np.array(new_df[['latitude', 'longitude']].values)
target = np.array([[target_lat, target_lon]])

distances = cdist(target, coords, metric='euclidean')
nearest_idx = distances.argmin(axis=1)
closest_row = new_df.iloc[nearest_idx[0]]
closest_row

pressure_level    300.000000
latitude           40.000000
longitude         -75.000000
u                  21.536186
v                   0.621516
number              0.000000
expver              1.000000
Name: 2025-10-01 00:00:00, dtype: float64

In [25]:
wind_x, wind_y = closest_row['u'], closest_row['v']
wind_x, wind_y

(np.float64(21.536186), np.float64(0.6215162))